apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: {{ getenv "ARGOCD_APP_NAMESPACE" "default" }}
type: Opaque
data:
  password: {{ (ds "ip").country | base64.Encode }}
  foo: {{ getenv "ARGOCD_ENV_CUSTOM_ENV_VARIABLE" | base64.Encode }} # argocd prepends the env vars with ARGOCD_ENV_
