configs:
  # -- Plugin yaml files to be added to argocd-cmp-cm
  cmp:
    create: true
    plugins:
      gomplate:
        generate:
          command: [sh, -c]
          args:
            # here we define our custom command to render the yaml file
            - cat ./* | gomplate -d ip=https://ipinfo.io

repoServer:
  extraContainers:
    - name: gomplate
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: alpine:3
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /usr/bin
          name: cmp-tmp
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: argocd-cmp-cm
          subPath: gomplate.yaml
  initContainers:
    - name: install-gomplate
      image: alpine:3
      command: ["sh", "-c"]
      args:
        # here we install gomplate binary
        - apk add --no-cache gomplate
      volumeMounts:
        - mountPath: /usr/bin
          name: cmp-tmp

  # -- Additional volumes to the repo server pod
  volumes:
    # This is the config map all the CMPs are defined
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
